name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@v3.33
        with:
          user: 4rjav
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: test
          plugin_languages_details: bytes-size, percentage

          # Plugin: Traffic
          plugin_traffic: yes

          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          # Plugin: Notable contributions
          plugin_notable: yes

          # Plugin: Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

          # Plugin: Stars
          plugin_stars: yes
          plugin_stars_limit: 5
